apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-85iv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-85iv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-85iv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-85iv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-85iv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-levy-tenant/rhtap-demo-app/hacbs-test-project-85iv@sha256:550b3b872f1c38e2f575ffea908589b2ba40b173df113478c56d5e3bbee38b5b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
